/**
 * The referee, on the wire.
 *
 * One function, one POST, one `action` per `PlayRequest`. Everything a table
 * does online goes through here, because this is the only participant that holds
 * the service role — the only one that may write the command log, read the seed,
 * or see the whole board. Every other participant is a browser with a seat and a
 * JWT, and 0002_policies.sql decides what that entitles it to read.
 *
 * Three rules run through the whole file.
 *
 * **Identity comes off the JWT and nowhere else.** The caller's account is read
 * by handing their `Authorization` header to a client built with the *anon* key
 * and asking Supabase who it belongs to. Nothing in the request body is ever
 * consulted for who somebody is; `by` inside a command is checked against the
 * seat that account holds, which is the one thing a relay cannot do and the
 * reason the field means anything.
 *
 * **The referee decides nothing.** `src/net/supabase/referee.ts` judges orders,
 * seats players, rolls the dice and redacts the board. This file reads rows,
 * calls one of those, and writes rows. When the two disagree the referee is
 * right, because the referee is the part with tests.
 *
 * **A half-written command is a corrupted game.** Accepting an order touches
 * four tables and PostgREST gives one transaction per request, so the four
 * writes are handed to `apply_command` in 0003_apply.sql and committed together.
 * The same function serialises concurrent orders and refuses the stale one; see
 * `commandAction` below and the header of that migration.
 *
 * ## The die
 *
 * Every seed this function rolls with comes from `crypto.getRandomValues` and
 * goes into the log beside the command it was used on. The stored board's own
 * generator is sealed to zero and never rolled with, so a leak of the state is
 * not a leak of the dice, and a replay of the log is still exact.
 *
 * ## The engine
 *
 * Deno cannot read this codebase's TypeScript: the imports carry a `.js`
 * extension that means `.ts` and reach through `@engine/`-style aliases. So the
 * rules arrive pre-bundled at `../_shared/engine.js`, which is generated by
 * `scripts/build-functions.mjs` and not committed. Run `npm run functions:build`
 * before deploying; `npm run functions:deploy` does it for you.
 */

import { createClient } from 'npm:@supabase/supabase-js@^2.112.3';

// Deno does not look for a declaration file beside a `.js` the way TypeScript's
// own resolver does — it needs to be told, and this is how. Without the line
// the bundle is untyped, every `type` import below fails, and the errors
// cascade into implicit-any on anything that touched them. The browser build
// resolves the same file through `tsconfig.functions.json` and ignores this
// comment, so the two agree on where the types come from.
// @deno-types="../_shared/engine.d.ts"
import {
  type Command,
  type CreateRequest,
  type GameState,
  type JoinRequest,
  type LoggedCommand,
  type PlayRequest,
  type PlayResponse,
  type SeatRow,
  type StoredGame,
  type SyncRequest,
  type TableResponse,
  CODE_LENGTH,
  PRESENCE_MS,
  SUPABASE_PROTOCOL_VERSION,
  TABLES,
  buildScenario,
  codeFrom,
  judge,
  leaveSeat,
  parsePlayRequest,
  playComputerSeats,
  scenarioById,
  sealDie,
  seatOf,
  tableInfo,
  takeSeat,
  viewFor,
  viewsForAll,
} from '../_shared/engine.js';
import {
  type GameRow,
  type SeatDbRow,
  type SecretRow,
  changedSeats,
  changedSeatsToDb,
  dieFrom,
  loggedFromDb,
  logRow,
  openingSeats,
  readyToStart,
  seatToInsert,
  setupFrom,
  storedGame,
  syncResponse,
} from './rules.ts';

// ---------------------------------------------------------------------------
// The two clients, and why there are two
// ---------------------------------------------------------------------------

const SUPABASE_URL = Deno.env.get('SUPABASE_URL') ?? '';
const ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY') ?? '';
const SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '';

/**
 * The referee's own client, and the only one that touches a table.
 *
 * `service_role` bypasses row level security, which is the entire point: the
 * policies exist to stop *players* reading the board, and the referee is not a
 * player. Nothing built from this client is ever handed a value from a request
 * body without the referee having decided it first.
 */
const admin = createClient(SUPABASE_URL, SERVICE_KEY, {
  auth: { persistSession: false, autoRefreshToken: false },
});

/** `game_secrets` is deliberately absent from `TABLES`: no client names it. */
const SECRETS = 'game_secrets';

// ---------------------------------------------------------------------------
// Answers
// ---------------------------------------------------------------------------

/**
 * Wide open, because the browser bundle is served from wherever the project
 * happens to be hosted and the JWT — not the origin — is what authorises
 * anything. A cross-origin caller with no token gets a 401 and a caller with one
 * is a player, whichever page they came from.
 */
const CORS: Record<string, string> = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Max-Age': '86400',
};

/**
 * Every answer this function gives is a `PlayResponse`, including the failures.
 *
 * A refusal the referee decided — an illegal move, a taken seat — is a 200,
 * because the request was understood and answered. The 4xx codes are reserved
 * for the envelope: a body that is not a request, a caller with no token, a verb
 * this function does not have. That split is what lets a client read
 * `body.reason` unconditionally instead of guessing whether the body is a
 * response or a gateway's error page.
 */
const answer = (body: PlayResponse, status = 200): Response =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS, 'content-type': 'application/json; charset=utf-8' },
  });

const refuse = (reason: string, status = 200, seq?: number): Response =>
  answer(seq === undefined ? { ok: false, reason } : { ok: false, reason, seq }, status);

/**
 * One refusal for every way a join can fail.
 *
 * Six characters out of an alphabet of thirty-one is a space worth walking, and
 * a message that distinguishes "no such table" from "that table is full" turns
 * this endpoint into an oracle that says which codes are live. It costs a
 * mistyped code a worse error message, which is the cheaper of the two.
 */
const NO_TABLE = 'no table is waiting on that code';

// ---------------------------------------------------------------------------
// Who is calling
// ---------------------------------------------------------------------------

/**
 * The account behind the request, or null.
 *
 * The header is verified by Supabase rather than parsed here. A JWT this
 * function decoded itself would be a JWT this function could get wrong, and
 * getting it wrong means seating an attacker as somebody else.
 */
const callerOf = async (req: Request): Promise<string | null> => {
  const authorization = req.headers.get('Authorization');
  if (authorization === null || authorization === '') return null;

  const scoped = createClient(SUPABASE_URL, ANON_KEY, {
    global: { headers: { Authorization: authorization } },
    auth: { persistSession: false, autoRefreshToken: false },
  });
  const { data, error } = await scoped.auth.getUser();
  if (error !== null || data.user === null) return null;
  return data.user.id;
};

// ---------------------------------------------------------------------------
// Reading a table
// ---------------------------------------------------------------------------

const GAME_COLUMNS = 'id, code, scenario_id, fog, status, turn, command_count, host_id';
const SEAT_COLUMNS = 'seat, ordinal, faction, name, kind, user_id, last_seen';

const fail = (what: string, error: { message: string } | null): void => {
  if (error !== null) throw new Error(`${what}: ${error.message}`);
};

/**
 * Load a whole table: the public row, the secret board, the roster.
 *
 * The order of the two reads is load-bearing and not an accident of style.
 * `command_count` comes from `games` and the board comes from `game_secrets`,
 * and the pair is handed to `apply_command` as "this board is the board at log
 * length N". Read the board first and a command landing in the gap makes N one
 * too *large* for the board we hold — and `apply_command`'s staleness check,
 * which compares N against the log, would wave it through and write a board a
 * move behind its own log. Read `games` first and the same race makes N one too
 * small, which that check catches and refuses. Same window, opposite outcome.
 */
interface Loaded {
  readonly game: StoredGame;
  /** The seed and setup choices, kept so an open sync can rebuild `initial`. */
  readonly setup: SecretRow;
}

const loadGame = async (by: 'id' | 'code', value: string): Promise<Loaded | null> => {
  const found = await admin.from(TABLES.games).select(GAME_COLUMNS).eq(by, value).maybeSingle();
  fail('reading the table', found.error);
  if (found.data === null) return null;
  const row = found.data as unknown as GameRow;

  const [secret, seats] = await Promise.all([
    admin.from(SECRETS).select('seed, options, fleets, state').eq('game_id', row.id).maybeSingle(),
    admin.from(TABLES.seats).select(SEAT_COLUMNS).eq('game_id', row.id),
  ]);
  fail('reading the board', secret.error);
  fail('reading the roster', seats.error);
  if (secret.data === null) return null;

  const setup = secret.data as unknown as SecretRow;
  return { game: storedGame(row, setup, (seats.data ?? []) as unknown as SeatDbRow[]), setup };
};

/**
 * The command log from `since` onwards, in pages.
 *
 * `max_rows = 200` in config.toml caps every PostgREST response, and it caps
 * silently — a long game read in one request would come back truncated and
 * replay to the wrong board with nothing anywhere saying so. So the log is read
 * until a short page arrives.
 */
const LOG_PAGE = 200;

const readLog = async (gameId: string, since: number): Promise<LoggedCommand[]> => {
  const out: LoggedCommand[] = [];
  for (;;) {
    // The cursor is the last index actually read, not `since` plus a count. The
    // log is gapless so the two agree, and taking it from the data means this
    // loop cannot spin if that ever stops being true.
    const from = out[out.length - 1]?.idx ?? since;
    const page = await admin
      .from(TABLES.commands)
      .select('idx, cmd, die')
      .eq('game_id', gameId)
      .gt('idx', from)
      .order('idx', { ascending: true })
      .range(0, LOG_PAGE - 1);
    fail('reading the log', page.error);
    const rows = (page.data ?? []) as unknown as { idx: number; cmd: Command; die: number }[];
    for (const row of rows) out.push(loggedFromDb(row));
    if (rows.length < LOG_PAGE) return out;
  }
};

// ---------------------------------------------------------------------------
// Dice
// ---------------------------------------------------------------------------

/**
 * A fresh seed, per command, from a source no player can see.
 *
 * "The seed for the next command does not exist until the command arrives."
 * That is the sentence the whole sealed-die design turns on, and this is the
 * function that has to be true for it.
 */
const rollDie = (): number => dieFrom(crypto.getRandomValues(new Uint8Array(4)));

// ---------------------------------------------------------------------------
// create
// ---------------------------------------------------------------------------

/**
 * How many codes to try before giving up.
 *
 * At 31^6 codes a collision is a coincidence, not a load. Six attempts turns a
 * pathologically full namespace into a clean refusal rather than a hang.
 */
const CODE_ATTEMPTS = 6;

/**
 * Sweep away lobbies nobody came back to.
 *
 * `0004_throttle.sql` says this is "called by the referee rather than
 * scheduled, so the migration needs no extension", and `0001_schema.sql` adds
 * `games_status_updated_idx` for exactly this query — but nothing ever called
 * it, so the sweep the design assumed was simply never happening.
 *
 * Create is the right moment. It is the only action that grows the namespace,
 * so tying the sweep to it keeps the table smallest where it matters most: an
 * abandoned lobby that still answers `join` is a live target for code guessing,
 * and every one removed is one fewer.
 *
 * It never fails a create. A player opening a table has no stake in the
 * housekeeping, and a sweep that errored — a lock, a timeout, a permission
 * changed underneath us — must not cost them their game. The failure is logged
 * and swallowed, deliberately, and the next create tries again.
 */
const reapLobbies = async (): Promise<void> => {
  const { error } = await admin.rpc('reap_stale_lobbies');
  if (error) console.error('reaping stale lobbies failed', error.message);
};

const createAction = async (req: CreateRequest, userId: string): Promise<Response> => {
  if (scenarioById(req.scenarioId) === undefined) return refuse('no scenario by that name');

  // A fogged scenario's secrets are a pure function of this number. Escape
  // picks the fugitive with `rollDie({seed: seedOf(opts)})`; Lateral 7 places
  // its dummies from the same draw. The host types the seed into the picker, so
  // honouring it here would hand them the opponent's hidden setup: rebuild the
  // scenario in their own browser, where the whole engine already ships, and
  // read it off. The field survives for open-information play, where the
  // starting position is sent to everybody anyway and a reproducible board is
  // worth having.
  const wantsFog = req.options?.['fogOfWar'] === true;
  const seed = !wantsFog && typeof req.seed === 'number' ? req.seed >>> 0 : rollDie();

  let opening: GameState;
  try {
    // The client chose the options and the fleets, so both are arbitrary JSON
    // until the scenario has looked at them. `buildScenario` is the thing that
    // knows what a hull is called; a refusal here is a bad request, not a bug.
    opening = sealDie(
      buildScenario(req.scenarioId, setupFrom(seed, req.options, req.fleets, req.order)),
    );
  } catch {
    return refuse('that scenario cannot be set up with those options');
  }

  const now = Date.now();
  const seats = openingSeats(opening, req.computerSeats, userId, req.name, now);

  // Fog is read off the built state, never off the request. "Which one is not
  // the client's choice — it is `TableInfo.fog`", and the state is where the
  // scenario recorded its answer.
  const fog = opening.options.fogOfWar;

  for (let attempt = 0; attempt < CODE_ATTEMPTS; attempt += 1) {
    const code = codeFrom(crypto.getRandomValues(new Uint8Array(CODE_LENGTH)));
    const { data, error } = await admin.rpc('create_game', {
      p_code: code,
      p_scenario: req.scenarioId,
      p_fog: fog,
      p_host: userId,
      p_seed: seed,
      p_options: opening.options,
      p_fleets: req.fleets ?? {},
      p_state: opening,
      p_turn: opening.turn,
      p_seats: seats.map(seatToInsert),
    });
    fail('opening the table', error);
    const result = data as { ok: boolean; id?: string; reason?: string } | null;
    if (result === null) throw new Error('create_game answered nothing');
    if (!result.ok) continue; // The only refusal it gives is a taken code.

    const game: StoredGame = {
      id: result.id ?? '',
      code,
      scenarioId: req.scenarioId,
      fog,
      status: 'lobby',
      state: opening,
      commandCount: 0,
      seats,
      hostId: userId,
    };
    // After the table exists, so a slow sweep delays the answer rather than
    // risking it, and awaited rather than left dangling — an Edge Function's
    // worker can be torn down the moment it responds.
    await reapLobbies();
    return answer(seated(game, userId, now));
  }

  return refuse('could not find a free join code; try again');
};

// ---------------------------------------------------------------------------
// join / leave
// ---------------------------------------------------------------------------

const seated = (game: StoredGame, userId: string, now: number): TableResponse => ({
  ok: true,
  table: tableInfo(game, userId, now),
  seat: seatOf(game, userId),
});

/**
 * Write a seat change, and the snapshot a new seat needs to see anything.
 *
 * The views argument is what stops a fog game handing a joining player a blank
 * board until somebody else moves: their `views` row does not exist yet, and
 * `views` is the only thing row level security lets them read.
 */
const writeSeats = async (
  game: StoredGame,
  userId: string,
  next: readonly SeatRow[],
  views: Record<string, GameState>,
): Promise<boolean> => {
  const changed = changedSeats(game.seats, next);
  if (changed.length === 0 && Object.keys(views).length === 0) return true;
  const { data, error } = await admin.rpc('save_seats', {
    p_game: game.id,
    p_user: userId,
    p_seats: changedSeatsToDb(changed),
    p_views: views,
  });
  fail('writing the roster', error);
  return (data as { ok: boolean } | null)?.ok === true;
};

const joinAction = async (req: JoinRequest, userId: string): Promise<Response> => {
  const loaded = await loadGame('code', req.code.toUpperCase());
  const hit = loaded !== null && loaded.game.status !== 'finished';

  // Charge for the guess before answering it. A miss is uniform and says
  // nothing, but a hit announces itself, so a loop over the code space is a
  // search with a payoff — and the only thing that makes it a bad one is the
  // budget. See 0004_throttle.sql. A failure to record is not a reason to
  // refuse a legitimate join: the throttle is a cost, not a gate.
  const { data: allowed, error: throttleError } = await admin.rpc('note_join_attempt', {
    p_user: userId,
    p_hit: hit,
  });
  if (throttleError !== null) console.warn('could not record the attempt', throttleError.message);
  if (allowed === false) return refuse(NO_TABLE);

  if (!hit || loaded === null) return refuse(NO_TABLE);
  const game = loaded.game;

  const now = Date.now();
  const change = takeSeat(game, userId, req.seat, req.name, now);
  if (!change.ok || change.seats === undefined) return refuse(NO_TABLE);

  const next = change.seats;
  const seat = change.seat ?? null;
  const views =
    game.fog && seat !== null && game.status === 'playing'
      ? { [seat]: viewFor({ ...game, seats: next }, seat) }
      : {};

  // A refusal here means somebody took the seat between the read and the write.
  // It is the same outcome as the seat having been taken all along, so it gets
  // the same answer.
  if (!(await writeSeats(game, userId, next, views))) return refuse(NO_TABLE);

  return answer(seated({ ...game, seats: next }, userId, now));
};

const leaveAction = async (game: StoredGame, userId: string): Promise<Response> => {
  const standing = game.seats.find((s) => s.userId === userId);
  const next = leaveSeat(game, userId);
  await writeSeats(game, userId, next, {});

  // Take the board out of the empty chair. The referee keeps a fresh snapshot
  // in `views` for every seat, and a vacated seat is one anybody may sit in —
  // so a row left behind is a fogged board waiting for whoever takes the chair
  // next. It is rewritten on the very next command for whoever is sitting there
  // by then, which is the only person entitled to it.
  if (standing !== undefined && game.fog) {
    const { error } = await admin
      .from('views')
      .delete()
      .eq('game_id', game.id)
      .eq('seat', standing.seat);
    if (error !== null) console.warn('could not clear the vacated view', error.message);
  }
  return answer(seated({ ...game, seats: next }, userId, Date.now()));
};

// ---------------------------------------------------------------------------
// start
// ---------------------------------------------------------------------------

/**
 * Close the lobby.
 *
 * Host only, and the host is `games.host_id` rather than "whoever is in seat
 * one" — the two come apart the moment the host hands their seat to somebody
 * else, and the person who opened the table is the one who should decide when it
 * begins.
 *
 * `playComputerSeats` runs immediately, so a solo table is already waiting on
 * the human by the time this returns rather than after some later poke.
 */
const startAction = async (game: StoredGame, userId: string): Promise<Response> => {
  if (game.hostId !== userId) return refuse('only the host may start this game');
  const notReady = readyToStart(game);
  if (notReady !== null) return refuse(notReady);

  const playing: StoredGame = { ...game, status: 'playing' };
  const out = playComputerSeats(playing, rollDie);
  const final = out.game;

  const written = await commit(final, game.commandCount, out.logged, seatOf(final, userId));
  if (!written.ok) return refuse('somebody else started this game first');
  return answer(seated(final, userId, Date.now()));
};

// ---------------------------------------------------------------------------
// command
// ---------------------------------------------------------------------------

/**
 * The four writes, as one.
 *
 * `expect` is the log length the new board was computed from. `apply_command`
 * takes the game's row lock, checks the log is still that long, and either
 * commits every row or commits none of them.
 *
 * The views are recomputed from the final board rather than taken from
 * `playComputerSeats`, which returns none when the computer had nothing to say —
 * and a fog game whose seats do not all get a fresh snapshot after every command
 * has some of them looking at a stale board.
 */
const commit = async (
  game: StoredGame,
  expect: number,
  logged: readonly LoggedCommand[],
  seat: string | null,
): Promise<{ ok: boolean }> => {
  const { data, error } = await admin.rpc('apply_command', {
    p_game: game.id,
    p_expect_count: expect,
    p_state: game.state,
    p_status: game.status,
    p_turn: game.state.turn,
    p_commands: logged.map(logRow),
    p_views: game.fog ? viewsForAll(game) : {},
    p_seat: seat,
  });
  fail('recording the command', error);
  const result = data as { ok: boolean; reason?: string } | null;
  return { ok: result?.ok === true };
};

/**
 * How many times to re-judge an order that lost a race.
 *
 * Retrying is safe because nothing is retried: the order is judged again from
 * the board as it now stands, so an order the intervening command made illegal
 * is refused on the rules rather than replayed. What is not safe is retrying
 * forever, which turns a busy table into a livelock.
 */
const COMMAND_ATTEMPTS = 3;

const commandAction = async (
  gameId: string,
  cmd: Command,
  userId: string,
  seq: number | undefined,
): Promise<Response> => {
  for (let attempt = 0; attempt < COMMAND_ATTEMPTS; attempt += 1) {
    const loaded = await loadGame('id', gameId);
    if (loaded === null) return refuse('no such table', 200, seq);
    const game = loaded.game;

    const seat = seatOf(game, userId);
    const verdict = judge(game, seat, cmd, rollDie());
    if (!verdict.ok) return refuse(verdict.reason, 200, seq);

    // The computer answers inside the same move. A human's order and every
    // order the referee's own seats gave in reply are one indivisible thing:
    // committing the first without the second would leave a board waiting on a
    // player that no longer has to act.
    const after = playComputerSeats(verdict.game, rollDie);
    const final = after.game;
    const logged = [verdict.logged, ...after.logged];

    const written = await commit(final, game.commandCount, logged, seat);
    if (written.ok) return answer({ ok: true, index: final.commandCount, seq });
  }

  return refuse('the table is busy; try that again', 200, seq);
};

// ---------------------------------------------------------------------------
// sync
// ---------------------------------------------------------------------------

/**
 * Catch up.
 *
 * A seated player gets what their seat is entitled to. A caller with no seat is
 * a spectator, and gets what `viewFor(game, null)` gives — everything in an open
 * game, only what is public in a fog one. That is a deliberate widening of the
 * database's own rule, which grants nothing for merely holding an id: a
 * spectator cannot read any of these tables directly and has no `views` row to
 * subscribe to, so the whole of their access is this call, through the referee,
 * filtered by the referee.
 */
const syncAction = async (req: SyncRequest, userId: string): Promise<Response> => {
  const loaded = await loadGame('id', req.gameId);
  if (loaded === null) return refuse('no such table');
  const { game, setup } = loaded;

  const seat = seatOf(game, userId);
  const since = typeof req.since === 'number' && req.since > 0 ? Math.floor(req.since) : 0;

  let open: { initial: GameState | null; log: readonly LoggedCommand[] } | null = null;
  if (!game.fog) {
    try {
      open = {
        // Only on a full sync. A tail is meant to be applied to the board the
        // client already holds, and sending the starting position beside it
        // invites exactly the mistake it caused: replay three commands onto
        // turn one and call it caught up.
        initial:
          since === 0
            ? buildScenario(
                game.scenarioId,
                // A campaign order is not stored on its own row: the opening
                // state embedded it in `scenarioData` at create, nothing in
                // play ever rewrites it, and the stored board is the same
                // state a few commands later — so it is read back from there.
                setupFrom(
                  setup.seed,
                  setup.options,
                  setup.fleets,
                  setup.state.scenarioData['order'],
                ),
              )
            : null,
        log: await readLog(game.id, since),
      };
    } catch {
      // The scenario the game was built from is no longer in this build. The
      // log cannot be replayed onto a starting position that cannot be
      // rebuilt, so fall back to shipping the board itself — worse for audit,
      // but a game somebody can still finish.
      open = null;
    }
  }

  // Presence, but only when it is actually stale.
  //
  // Writing it unconditionally is a loop with no exit: `touch_seat` sets
  // `last_seen = now()`, which is a genuine row change, which `seats` streams
  // to every client at the table, each of which re-syncs, each of which writes
  // its presence again. Half of `PRESENCE_MS` keeps the dot accurate and turns
  // the storm into one write per seat per twenty-odd seconds.
  const mine = seat === null ? undefined : game.seats.find((s) => s.seat === seat);
  const stale =
    mine !== undefined && (mine.lastSeen === null || Date.now() - mine.lastSeen > PRESENCE_MS / 2);
  if (stale) {
    // A failed presence write must not lose the sync: the caller is asking to
    // catch up, and a dimmed dot beats an error page.
    const { error } = await admin.rpc('touch_seat', { p_game: game.id, p_seat: seat });
    if (error !== null) console.warn('could not record presence', error.message);
  }

  return answer(syncResponse(game, seat, userId, Date.now(), open));
};

// ---------------------------------------------------------------------------
// Dispatch
// ---------------------------------------------------------------------------

const dispatch = async (req: PlayRequest, userId: string): Promise<Response> => {
  switch (req.action) {
    case 'create':
      return createAction(req, userId);
    case 'join':
      return joinAction(req, userId);
    case 'sync':
      return syncAction(req, userId);
    case 'command':
      return commandAction(req.gameId, req.cmd, userId, req.seq);
    case 'leave':
    case 'start': {
      const loaded = await loadGame('id', req.gameId);
      if (loaded === null) return refuse('no such table');
      return req.action === 'leave'
        ? leaveAction(loaded.game, userId)
        : startAction(loaded.game, userId);
    }
  }
};

Deno.serve(async (request: Request): Promise<Response> => {
  if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: CORS });
  if (request.method !== 'POST') {
    return refuse('this referee only answers POST', 405);
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return refuse('that request was not JSON', 400);
  }

  // Version before shape, because an old client in the wild is by far the most
  // likely reason a well-formed request fails to parse, and "malformed" is a
  // uselessly wrong thing to tell it.
  const version = (body as { v?: unknown } | null)?.v;
  if (version !== SUPABASE_PROTOCOL_VERSION) {
    return refuse(`this referee speaks protocol ${String(SUPABASE_PROTOCOL_VERSION)}`, 400);
  }

  const parsed = parsePlayRequest(body);
  if (parsed === null) return refuse('that is not a request this referee understands', 400);

  const userId = await callerOf(request);
  if (userId === null) return refuse('sign in before sitting down', 401);

  try {
    return await dispatch(parsed, userId);
  } catch (thrown) {
    // The message may name a table, a column or a constraint. That belongs in
    // the logs, where the person who can fix it is looking, and nowhere near a
    // response body.
    console.error('game function failed', thrown);
    return refuse('the referee could not answer that just now', 500);
  }
});
