-- ---------------------------------------------------------------------------
-- The referee's write path: four statements that are one statement.
--
-- Accepting a command touches four tables. The board in `game_secrets`, the log
-- in `commands`, a redacted snapshot per seat in `views`, and the turn and
-- status in `games`. Every one of them has to land or none of them can, because
-- the four disagree in different and unrecoverable ways:
--
--   * state written, log not written  — the board has moved and nothing records
--     why. Replay no longer reproduces it, and the audit trail the whole
--     open-information design rests on is a fiction.
--   * log written, state not written  — the next command is judged against a
--     board one move behind the log it will be appended to, and every replay
--     from that point diverges from what the referee actually did.
--   * views written, log not written  — a fog player is looking at a future
--     that officially never happened.
--
-- PostgREST gives one transaction per request, so four requests are four
-- transactions and a dropped connection between the second and the third leaves
-- a game in exactly those states. There is no client-side fix: retrying is not
-- idempotent, and the half-written game is already corrupt by the time the retry
-- is decided on. So the four writes are moved into the database and called as
-- one request. That is the whole reason this file exists.
--
-- ## Concurrency
--
-- Two commands arriving together are the same problem seen from the other end.
-- The Edge Function reads a game, computes the next board from it, and writes;
-- if a second command is read, computed and written in between, one of the two
-- has computed from a board that no longer exists.
--
-- Both halves are handled here, and both are needed:
--
--   * `select ... for update` on the `games` row serialises the writes. Two
--     callers cannot be inside the write half of this function for the same
--     game at once, whatever PostgREST's connection pool does with them.
--   * `p_expect_count` catches the stale one. The caller says which log length
--     it computed against; if the log has grown since, its board is out of date
--     and the call is refused rather than applied. `commands`' own gapless
--     trigger would refuse the insert anyway, but as an error after a partial
--     rollback rather than as an answer the function can give.
--
-- The refusal is a returned value, not an exception, because "you were beaten to
-- it" is an ordinary outcome the caller resyncs and retries from — while a
-- constraint violation genuinely is an exception and must roll the whole call
-- back. Keeping the two distinguishable is the point.
--
-- ## Why these are not `security definer`
--
-- Everything here writes tables no client may write. Running them as the owner
-- would mean one mistaken grant hands a player the board; running them as the
-- caller means the grants and the row level security in 0002 still stand behind
-- them, and only `service_role` — which bypasses those by design, and which only
-- the Edge Function holds — can get any of this to do anything. Two layers, same
-- as everywhere else in this schema.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- create_game — a table exists, or it does not
-- ---------------------------------------------------------------------------

-- A `games` row without its `game_secrets` row is a game with no board: it
-- lists in a lobby, it accepts a join, and it cannot be played or repaired. So
-- the three inserts are one call.
--
-- The join code is generated by the caller, from `crypto.getRandomValues`,
-- because that is where unguessable randomness lives — but uniqueness can only
-- be decided here, at the insert. A collision comes back as an ordinary refusal
-- so the caller can draw another code and try again; every other unique
-- violation is a bug and is re-raised.
create or replace function public.create_game(
  p_code     text,
  p_scenario text,
  p_fog      boolean,
  p_host     uuid,
  p_seed     bigint,
  p_options  jsonb,
  p_fleets   jsonb,
  p_state    jsonb,
  p_turn     integer,
  p_seats    jsonb
)
returns jsonb
language plpgsql
set search_path = ''
as $$
declare
  v_id         uuid;
  v_constraint text;
begin
  insert into public.games (code, scenario_id, fog, status, turn, host_id)
  values (p_code, p_scenario, p_fog, 'lobby', p_turn, p_host)
  returning id into v_id;

  insert into public.game_secrets (game_id, seed, options, fleets, state)
  values (v_id, p_seed, p_options, p_fleets, p_state);

  insert into public.seats (game_id, seat, ordinal, faction, name, kind, user_id, last_seen)
  select v_id, e.seat, e.ordinal, e.faction, e.name, e.kind, e.user_id, e.last_seen
    from jsonb_to_recordset(p_seats)
      as e(seat text, ordinal integer, faction text, name text, kind text,
           user_id uuid, last_seen timestamptz);

  return jsonb_build_object('ok', true, 'id', v_id);
exception
  when unique_violation then
    get stacked diagnostics v_constraint = constraint_name;
    if v_constraint = 'games_code_key' then
      -- Both inserts above are undone with this block. The caller draws a new
      -- code and calls again; nothing of the abandoned game survives.
      return jsonb_build_object('ok', false, 'reason', 'code-taken');
    end if;
    raise;
end;
$$;

-- ---------------------------------------------------------------------------
-- apply_command — the board, the log, the views and the turn, together
-- ---------------------------------------------------------------------------

-- `p_commands` is an array of `{idx, by, cmd, die}` in log order, which is more
-- than one row whenever the computer answered: a human's order and every order
-- the referee's own seats gave in reply are one indivisible move of the game.
--
-- `p_views` is `{seat: state}` and is empty for an open-information game, where
-- the log is the transport and a snapshot would be a second, redundant copy of a
-- board every seat can already compute.
--
-- Note what is not a parameter: `games.command_count`. The trigger in 0001
-- maintains it from the log itself. "Two places that both remember how long the
-- log is will eventually disagree", and a writer that could pass its own count
-- is the second place.
create or replace function public.apply_command(
  p_game         uuid,
  p_expect_count integer,
  p_state        jsonb,
  p_status       text,
  p_turn         integer,
  p_commands     jsonb,
  p_views        jsonb,
  p_seat         text
)
returns jsonb
language plpgsql
set search_path = ''
as $$
declare
  v_count integer;
  v_entry jsonb;
  v_idx   integer;
begin
  -- The lock, and the read that the staleness test compares against, are the
  -- same statement. Anything less leaves a window between them.
  select g.command_count into v_count
    from public.games g
   where g.id = p_game
     for update;

  if not found then
    return jsonb_build_object('ok', false, 'reason', 'gone');
  end if;

  if v_count <> p_expect_count then
    return jsonb_build_object('ok', false, 'reason', 'stale', 'index', v_count);
  end if;

  update public.game_secrets set state = p_state where game_id = p_game;

  -- Ordered, and a loop rather than one `insert ... select`, because the
  -- gapless trigger fires per row and judges each index against the log so far.
  -- A set insert would be relying on the planner to preserve an order it never
  -- promised.
  for v_entry in
    select e.value
      from jsonb_array_elements(p_commands) as e(value)
     order by (e.value->>'idx')::integer
  loop
    insert into public.commands (game_id, idx, by, cmd, die)
    values (
      p_game,
      (v_entry->>'idx')::integer,
      v_entry->>'by',
      v_entry->'cmd',
      (v_entry->>'die')::bigint
    );
  end loop;

  v_idx := p_expect_count + coalesce(jsonb_array_length(p_commands), 0);

  -- "so a client can spot a stale row": every snapshot written here reflects
  -- the log as it stands at the end of this call, so they all carry the same
  -- index.
  insert into public.views (game_id, seat, idx, state)
  select p_game, v.key, v_idx, v.value
    from jsonb_each(p_views) as v
  on conflict (game_id, seat)
    do update set idx = excluded.idx, state = excluded.state;

  update public.games
     set status = p_status,
         turn = p_turn
   where id = p_game;

  -- Presence is a side effect of playing, not a separate heartbeat: a seat that
  -- just gave an order is plainly still at the table.
  if p_seat is not null then
    update public.seats set last_seen = now()
     where game_id = p_game and seat = p_seat;
  end if;

  return jsonb_build_object('ok', true, 'index', v_idx);
end;
$$;

-- ---------------------------------------------------------------------------
-- save_seats — sitting down, without two people landing on the same chair
-- ---------------------------------------------------------------------------

-- `takeSeat` decides who sits where, and it decides it from a snapshot read one
-- round trip ago. Two friends clicking the same open seat at the same moment
-- both read it open, and the second write would silently evict the first.
--
-- So the claim is tested and taken under the same `games` row lock the command
-- path uses: the test below runs after the lock and the write runs before it is
-- released, which is what makes it a claim rather than an assumption. The test
-- is deliberately before the update, so a refusal has changed nothing and can be
-- returned rather than raised.
--
-- The update's own `user_id is null or user_id = p_user` predicate is the second
-- layer. It is what stops a stale snapshot from vacating somebody else's seat:
-- `takeSeat` writes the seat it is leaving as well as the seat it is taking, and
-- a snapshot old enough to be wrong about the first would otherwise throw a
-- stranger out of it.
create or replace function public.save_seats(
  p_game  uuid,
  p_user  uuid,
  p_seats jsonb,
  p_views jsonb
)
returns jsonb
language plpgsql
set search_path = ''
as $$
declare
  v_count integer;
begin
  select g.command_count into v_count
    from public.games g
   where g.id = p_game
     for update;

  if not found then
    return jsonb_build_object('ok', false, 'reason', 'gone');
  end if;

  if exists (
    select 1
      from jsonb_to_recordset(p_seats) as e(seat text, user_id uuid)
      join public.seats s on s.game_id = p_game and s.seat = e.seat
     where e.user_id = p_user
       and s.user_id is not null
       and s.user_id <> p_user
  ) then
    return jsonb_build_object('ok', false, 'reason', 'taken');
  end if;

  update public.seats s
     set name      = e.name,
         kind      = e.kind,
         user_id   = e.user_id,
         last_seen = e.last_seen
    from jsonb_to_recordset(p_seats)
      as e(seat text, name text, kind text, user_id uuid, last_seen timestamptz)
   where s.game_id = p_game
     and s.seat = e.seat
     and (s.user_id is null or s.user_id = p_user);

  -- A seat that joins a fog game already in progress has no snapshot until the
  -- next command is played, and a board it cannot see is not a game. One is
  -- written here so it has something to render immediately.
  insert into public.views (game_id, seat, idx, state)
  select p_game, v.key, v_count, v.value
    from jsonb_each(p_views) as v
  on conflict (game_id, seat)
    do update set idx = excluded.idx, state = excluded.state;

  return jsonb_build_object('ok', true, 'index', v_count);
end;
$$;

-- ---------------------------------------------------------------------------
-- touch_seat — the presence dot
-- ---------------------------------------------------------------------------

-- Split out from `save_seats` because a sync writes nothing else, and rewriting
-- every seat row of a table to record that one of them said hello would stream a
-- roster change to everybody at it.
create or replace function public.touch_seat(p_game uuid, p_seat text)
returns void
language sql
set search_path = ''
as $$
  update public.seats
     set last_seen = now()
   where game_id = p_game and seat = p_seat;
$$;

-- ---------------------------------------------------------------------------
-- Who may call these
-- ---------------------------------------------------------------------------

-- `create function` grants EXECUTE to PUBLIC, and every function above writes
-- tables that exist to be unwritable. The default is withdrawn and handed back
-- to the one role the Edge Function holds. Even without this the functions are
-- invoker-rights and would be stopped by the grants in 0002 — but a caller who
-- can reach a function that then fails is a caller who has learnt something,
-- and there is nothing here worth learning.
revoke execute on function
  public.create_game(text, text, boolean, uuid, bigint, jsonb, jsonb, jsonb, integer, jsonb),
  public.apply_command(uuid, integer, jsonb, text, integer, jsonb, jsonb, text),
  public.save_seats(uuid, uuid, jsonb, jsonb),
  public.touch_seat(uuid, text)
from public, anon, authenticated;

grant execute on function
  public.create_game(text, text, boolean, uuid, bigint, jsonb, jsonb, jsonb, integer, jsonb),
  public.apply_command(uuid, integer, jsonb, text, integer, jsonb, jsonb, text),
  public.save_seats(uuid, uuid, jsonb, jsonb),
  public.touch_seat(uuid, text)
to service_role;
